[workspace]
resolver = "2"
members = ["examples/async_functions","examples/basic_tracing",
    "tracing_json",
    "tracing_json_derive",
]

#[patch.crates-io]
#tracing_json = { path = "tracing_json" }

